In [52]:
# 🤖 NumPy ve Pandas Uygulamalı Etkinliği - Yapay Zekâya Giriş
# --------------------------------------------------------------
# Bu çalışmada NumPy ve Pandas kütüphanelerini uygulamalı olarak öğreneceksiniz.
# Kodları kendiniz yazarak parametrelerin ne işe yaradığını anlamaya çalışın.
# Her görevden sonra, kodunuzu ve açıklamanızı ilgili alana yazın.

In [2]:
# =============================================================
# 1. NUMPY - SAYISAL VERİ İŞLEME
# =============================================================

# 1.1 NumPy Kütüphanesini Dahil Et
# Görev: NumPy kütüphanesini içe aktarın ve sürümünü ekrana yazdırın.
# Soru: 'as np' ifadesi ne işe yarıyor olabilir?

# 💻 Kodunuzu buraya yazın:
import numpy as np

# 📝 Cevap: as np ile kutuphaneye takma ısım verırız bu sayede kod yazarken onu cagırmak daha

In [63]:
# --------------------------------------------------------------
# 1.2 NumPy Dizisi Oluşturma
# Görev: 0'dan 10'a kadar sayılardan oluşan bir NumPy dizisi oluşturun.
# Soru: np.arange() içindeki parametreler neyi belirler?

# 💻 Kodunuzu buraya yazın:
dizi=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(dizi)
# 📝 Cevap:
"""
np.arange() içine "başlangıç, bitiş, artış" olarak üç parametre girer.
np.arrange(2,30,2) kodu 2'den başlayarak 30'a kadar yazdırır fakat ikişer ikişer arttırır... 2,4,6,8,10...,30
""" 

[ 0  1  2  3  4  5  6  7  8  9 10]


'\nnp.arange() içine "başlangıç, bitiş, artış" olarak üç parametre girer.\nnp.arrange(2,30,2) kodu 2\'den başlayarak 30\'a kadar yazdırır fakat ikişer ikişer arttırır... 2,4,6,8,10...,30\n'

In [67]:
# --------------------------------------------------------------
# 1.3 Diziyi İnceleme
# Görev: Dizinin boyutu, eleman sayısı ve veri tipini yazdırın.
# Soru: ndim, size ve dtype ne işe yarar?

# 💻 Kodunuzu buraya yazın:
print(dizi.ndim)
print(dizi.size)
print(dizi.dtype)
# 📝 Cevap:
"""
ndim: dizinin boyutunu verir
size: dizinin toplam eleman sayısını verir
dtype: dizinin elemanlarının veri tipini verir
"""


1
11
int64


'\nndim: dizinin boyutunu verir\nsize: dizinin toplam eleman sayısını verir\ndtype: dizinin elemanlarının veri tipini verir\n'

In [ ]:
# --------------------------------------------------------------
# 1.4 Sıfır ve Bir Dizileri
# Görev: 2 satır, 4 sütundan oluşan sıfırlardan ve birlerden diziler oluşturun.
# Soru: np.zeros((satir, sutun)) yapısındaki parantez neden iki katlı?

# 💻 Kodunuzu buraya yazın:
sifir = np.zeros((2, 4))
print("Sıfırlardan oluşan dizi:")
print(sifir)
#########
bir = np.ones((2, 4))
print("\nBirlerden oluşan dizi:")
print(bir)
# eğer aynı dizide 0 ve 1 oluşturmak istersek np.random.randint(0, 2, (2, 4))

# 📝 Cevap:
"""
dıştaki parantez fonksiyon içindir, içteki parantez ise dizinin boyutlarını belirten kısımdır 
"""



Sıfırlardan oluşan dizi:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Birlerden oluşan dizi:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


'\ndıştaki parantez fonksiyon içindir, içteki parantez ise dizinin boyutlarını belirten kısımdır \n'

In [71]:
# --------------------------------------------------------------
# 1.5 Rastgele Sayılardan Dizi
# Görev: 0 ile 100 arasında rastgele 5 sayıdan oluşan bir dizi oluşturun.
# Soru: randint() fonksiyonundaki parametreler neyi kontrol eder?

# 💻 Kodunuzu buraya yazın:
rastgele_dizi=np.random.randint(0,100,5)
print(rastgele_dizi)
# 📝 Cevap:
"""
birinci parametre başlangıç sayısı
ikinci parametre bitiş sayısı
dizinin eleman sayısı
"""



[99 24  0 87 70]


'\nbirinci parametre başlangıç sayısı\nikinci parametre bitiş sayısı\ndizinin eleman sayısı\n'

In [6]:
# --------------------------------------------------------------
# 1.6 Dizilerle İşlemler
# Görev: İki farklı NumPy dizisi (a ve b) oluşturup toplama, çıkarma, çarpma, bölme yapın.
# Soru: Bu işlemler eleman bazında mı yoksa dizi bazında mı olur?

# 💻 Kodunuzu buraya yazın:
a=np.array([11,12,13,14,15,16,17,18,19,20])
b=np.array([1,2,3,4,5,6,7,8,9,10])
print( a + b) #toplama
print(a - b) #çıkarma
print(a * b) #çarpma
print(a / b) #bölme
# 📝 Cevap:
""""
bütün elemanlar teker teker etkilenir yani eleman azında gerçekleşir
her bir eleman aynı indiste ki elemanla işlem görür
"""

[12 14 16 18 20 22 24 26 28 30]
[10 10 10 10 10 10 10 10 10 10]
[ 11  24  39  56  75  96 119 144 171 200]
[11.          6.          4.33333333  3.5         3.          2.66666667
  2.42857143  2.25        2.11111111  2.        ]


'"\nbütün elemanlar teker teker etkilenir yani eleman azında gerçekleşir\nher bir eleman aynı indiste ki elemanla işlem görür\n'

In [7]:
# --------------------------------------------------------------
# 1.7 İndeksleme ve Dilimleme
# Görev: 10'dan 20'ye kadar sayılardan oluşan bir dizi oluşturun.
#  - İlk 4 elemanı, son 2 elemanı ve ortadaki 3 elemanı seçin.
# Soru: [baslangic:bitis] yapısındaki sayılar neyi belirler?

# 💻 Kodunuzu buraya yazın:
indeksleme_dilimleme=np.array([10,11,12,13,14,15,16,17,18,19,20])
print(indeksleme_dilimleme[:4])  
print(indeksleme_dilimleme[-2:]) 
print(indeksleme_dilimleme[4:7]) 
# 📝 Cevap:diziden hangi aralıktaki elemanların seçileceğini belirler.




[10 11 12 13]
[19 20]
[14 15 16]


In [101]:
# --------------------------------------------------------------
# 1.8 Basit İstatistiksel İşlemler
# Görev: 6 nottan oluşan bir NumPy dizisi oluşturup ortalama, maksimum, minimum bulun.
# Soru: np.mean(), np.max(), np.min() fonksiyonlarının parametreleri ne işe yarar?

# 💻 Kodunuzu buraya yazın:
notlar = np.array([70, 85, 90, 60, 75, 80])
print(notlar.mean()) 
print(notlar.max())
print(notlar.min())

# 📝 Cevap:
"""
np.mean() dizideki elemanların ortalmasını bulur
np.max()    ""         ""         en büyük değerini bulur
np.min()    ""         ""         en küçük    ""     ""
"""



76.66666666666667
90
60


'\nnp.mean() dizideki elemanların ortalmasını bulur\nnp.max()    ""         ""         en büyük değerini bulur\nnp.min()    ""         ""         en küçük    ""     ""\n'

In [9]:
# =============================================================
# 2. PANDAS - TABLOLARLA VERİ ANALİZİ
# =============================================================

# 2.1 Pandas Kütüphanesini Dahil Et
# Görev: Pandas kütüphanesini içe aktarın ve sürümünü yazdırın.
# Soru: 'as pd' neden kullanılır?

# 💻 Kodunuzu buraya yazın:
import pandas as pd 

# 📝 Cevap: as pd ile kutuphaneye takma ısım verırız bu sayede kod yazarken onu cagırmak daha

In [13]:
# --------------------------------------------------------------
# 2.2 Basit Bir Tablo (DataFrame) Oluşturma
# Görev: Aşağıdaki bilgileri kullanarak bir tablo oluşturun:
# Ad | Yaş | Not
# Ali | 17 | 85
# Zeynep | 18 | 90
# Ayşe | 17 | 70
# Soru: DataFrame yapısında satır ve sütunlar nasıl gösterilir?

# 💻 Kodunuzu buraya yazın:
liste= {'Ad':['Ali','Zeynep','Ayşe'], 'Yaş':[17,18,17], 'Not':[85,90,70]}
df=pd.DataFrame(liste)
print(df)
# 📝 Cevap:
"""
       Ad  Yaş  Not
0     Ali   17   85
1  Zeynep   18   90
2    Ayşe   17   70

şeklinde gösterilir, kodda yazdıgımızdan farklı olarak satırların solunda indeks numaraları gösterilir
"""



       Ad  Yaş  Not
0     Ali   17   85
1  Zeynep   18   90
2    Ayşe   17   70


'\n       Ad  Yaş  Not\n0     Ali   17   85\n1  Zeynep   18   90\n2    Ayşe   17   70\n\nşeklinde gösterilir, kodda yazdıgımızdan farklı olarak satırların solunda indeks numaraları gösterilir\n'

In [18]:
# --------------------------------------------------------------
# 2.3 Sütun ve Satır Seçme
# Görev: Sadece 'Ad' sütununu ve 2. satırı görüntüleyin.
# Soru: iloc[] ve loc[] arasındaki fark nedir?

# 💻 Kodunuzu buraya yazın:
print(df.loc[1:2,"Ad"])

# 📝 Cevap:
"""
iloc: konum (index) olarak seçim yapar. Yani satır ve sütunları sıfırdan başlayan sayılarla seçersin.
loc: etiket (label) olarak seçim yapar. Yani satır ve sütun isimlerini kullanırsın
"""



1    Zeynep
2      Ayşe
Name: Ad, dtype: object


'\niloc: konum (index) olarak seçim yapar. Yani satır ve sütunları sıfırdan başlayan sayılarla seçersin.\nloc: etiket (label) olarak seçim yapar. Yani satır ve sütun isimlerini kullanırsın\n'

In [19]:
# --------------------------------------------------------------
# 2.4 Filtreleme
# Görev: Notu 80'den büyük olan öğrencileri listeleyin.
# Soru: Filtreleme işlemlerinde >, <, == sembolleri nasıl kullanılır?

# 💻 Kodunuzu buraya yazın:
ogrenci_listele = df["Not"] > 80
print(df[ogrenci_listele])

# 📝 Cevap:
"""
bu semboller karşılaştırma operatörleridir
belirlenen koşulun karşılanıp karşılanmadığını kontrol ederiz
 > bir değerin diğer değer veya değerlerden büyük olup olmadığını kontrol eder  
 < bir değerin diğer değer veya değerlerden küçük olup olmadığını kontrol eder  
 == bir değerin diğer değer veya değerlere eşit olup olmadığını kontrol eder  
"""

       Ad  Yaş  Not
0     Ali   17   85
1  Zeynep   18   90


'\nbu semboller karşılaştırma operatörleridir\nbelirlenen koşulun karşılanıp karşılanmadığını kontrol ederiz\n > bir değerin diğer değer veya değerlerden büyük olup olmadığını kontrol eder  \n < bir değerin diğer değer veya değerlerden küçük olup olmadığını kontrol eder  \n == bir değerin diğer değer veya değerlere eşit olup olmadığını kontrol eder  \n'

In [ ]:
# --------------------------------------------------------------
# 2.5 Ortalama Hesaplama
# Görev: Sınıfın ortalama notunu hesaplayın.
# Soru: mean() fonksiyonu sayısal olmayan sütunlarda çalışır mı?

# 💻 Kodunuzu buraya yazın:
print(df["Not"].mean())

# 📝 Cevap: hayır sadece sayısal verilerde çalışır




81.66666666666667


In [123]:
# --------------------------------------------------------------
# 2.6 Ek Görev (isteğe bağlı)
# Görev: 3 kitap ve fiyatından oluşan bir tablo oluşturun, en pahalı kitabı bulun.
# Soru: sort_values() fonksiyonundaki ascending parametresi ne işe yarar?

# 💻 Kodunuzu buraya yazın:
df = pd.DataFrame({"Kitap": ["Çalıkuşu", "Aşk-ı Memu", "Beyaz Geceler"], "Fiyat": [198, 107, 66]})
pahali = df.sort_values("Fiyat", ascending=False).iloc[0]
print(pahali)
# 📝 Cevap:
"""
artan mı yoksa azalan mı sıralanacağını belirler
ascending=True küçükten büyüğe
ascending=False büyükten küçüğe
"""



Kitap    Çalıkuşu
Fiyat         198
Name: 0, dtype: object


'\nartan mı yoksa azalan mı sıralanacağını belirler\nascending=True küçükten büyüğe\nascending=False büyükten küçüğe\n'